name: projet devops ci cd

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Configuration de JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'
        distribution: 'adopt'
        cache: maven
    - name: Compilation avec Maven et exécution des tests
      run: mvn clean install test
    - name: Exécution des tests JUnit et génération du rapport
      run: |
        mkdir -p junit-report
        find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} junit-report/ \;
    - name: Construction et déploiement de l'image Docker
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: diamankasn/m2gl-devops-pipeline-ci-cd
        tags: latest
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
